<?php
declare (strict_types = 1);

/**
 * 控制器@方法 => 所需权限码（全部满足）；空数组表示仅需登录；未配置的键在 AdminRbac 中默认放行（便于扩展）
 */
return [
    'map' => [
        'Auth@profile' => [],
        'Auth@permissions' => [],
        'Auth@menus' => [],

        'Dashboard@overview' => ['dashboard:view'],

        'Order@timeoutJobStatus' => ['system:job:view'],
        'Order@list' => ['order:manage'],
        'Order@detail' => ['order:manage'],
        'Order@refund' => ['order:refund'],
        'Order@statistics' => ['order:manage'],

        'User@list' => ['user:manage'],
        'User@detail' => ['user:manage'],
        'User@updateStatus' => ['user:manage'],
        'User@deviceList' => ['device:manage'],
        'User@deviceDelete' => ['device:manage'],

        'Content@dramaList' => ['content:drama:manage'],
        'Content@dramaCreate' => ['content:drama:manage'],
        'Content@dramaUpdate' => ['content:drama:manage'],
        'Content@dramaDelete' => ['content:drama:manage'],
        'Content@episodeList' => ['content:episode:manage'],
        'Content@episodeCreate' => ['content:episode:manage'],
        'Content@episodeUpdate' => ['content:episode:manage'],
        'Content@episodeDelete' => ['content:episode:manage'],
        'Content@novelList' => ['content:novel:manage'],
        'Content@novelCreate' => ['content:novel:manage'],
        'Content@novelUpdate' => ['content:novel:manage'],
        'Content@novelDelete' => ['content:novel:manage'],
        'Content@chapterList' => ['content:chapter:manage'],
        'Content@chapterCreate' => ['content:chapter:manage'],
        'Content@chapterUpdate' => ['content:chapter:manage'],
        'Content@chapterDelete' => ['content:chapter:manage'],
        'Content@categoryList' => ['content:category:manage'],
        'Content@categoryCreate' => ['content:category:manage'],
        'Content@categoryUpdate' => ['content:category:manage'],
        'Content@categoryDelete' => ['content:category:manage'],
        'Content@tagList' => ['content:tag:manage'],
        'Content@tagCreate' => ['content:tag:manage'],
        'Content@tagUpdate' => ['content:tag:manage'],
        'Content@tagDelete' => ['content:tag:manage'],
        'Content@audit' => ['content:audit'],
        'Content@dramaCategoryList' => ['content:drama:category:manage'],
        'Content@dramaCategoryCreate' => ['content:drama:category:manage'],
        'Content@dramaCategoryUpdate' => ['content:drama:category:manage'],
        'Content@dramaCategoryDelete' => ['content:drama:category:manage'],
        'Content@dramaTagList' => ['content:drama:tag:manage'],
        'Content@dramaTagCreate' => ['content:drama:tag:manage'],
        'Content@dramaTagUpdate' => ['content:drama:tag:manage'],
        'Content@dramaTagDelete' => ['content:drama:tag:manage'],
        'Content@novelCategoryList' => ['content:novel:category:manage'],
        'Content@novelCategoryCreate' => ['content:novel:category:manage'],
        'Content@novelCategoryUpdate' => ['content:novel:category:manage'],
        'Content@novelCategoryDelete' => ['content:novel:category:manage'],
        'Content@novelTagList' => ['content:novel:tag:manage'],
        'Content@novelTagCreate' => ['content:novel:tag:manage'],
        'Content@novelTagUpdate' => ['content:novel:tag:manage'],
        'Content@novelTagDelete' => ['content:novel:tag:manage'],
        'Content@dramaAudit' => ['content:drama:audit'],
        'Content@novelAudit' => ['content:novel:audit'],

        'Member@levelList' => ['member:manage'],
        'Member@levelCreate' => ['member:manage'],
        'Member@levelUpdate' => ['member:manage'],
        'Member@levelDelete' => ['member:manage'],
        'Member@userList' => ['member:manage'],

        'Distribution@recordList' => ['distribution:manage'],
        'Distribution@withdrawList' => ['distribution:manage'],
        'Distribution@withdrawAudit' => ['distribution:manage'],
        'Distribution@configGet' => ['distribution:manage'],
        'Distribution@configSet' => ['distribution:manage'],

        'Ad@positionList' => ['ad:position:manage'],
        'Ad@positionCreate' => ['ad:position:manage'],
        'Ad@positionUpdate' => ['ad:position:manage'],
        'Ad@positionDelete' => ['ad:position:manage'],
        'Ad@list' => ['ad:manage'],
        'Ad@create' => ['ad:manage'],
        'Ad@update' => ['ad:manage'],
        'Ad@delete' => ['ad:manage'],
        'Ad@statistics' => ['ad:manage'],

        'News@list' => ['content:news:manage'],
        'News@create' => ['content:news:manage'],
        'News@update' => ['content:news:manage'],
        'News@delete' => ['content:news:manage'],

        'FlashSale@activityList' => ['marketing:flash-sale:manage'],
        'FlashSale@activityCreate' => ['marketing:flash-sale:manage'],
        'FlashSale@activityUpdate' => ['marketing:flash-sale:manage'],
        'FlashSale@activityPublish' => ['marketing:flash-sale:manage'],
        'FlashSale@activityClose' => ['marketing:flash-sale:manage'],
        'FlashSale@activityCopy' => ['marketing:flash-sale:manage'],
        'FlashSale@activityBatchCopy' => ['marketing:flash-sale:manage'],
        'FlashSale@activityBatchStatus' => ['marketing:flash-sale:manage'],
        'FlashSale@itemList' => ['marketing:flash-sale:manage'],
        'FlashSale@itemCreate' => ['marketing:flash-sale:manage'],
        'FlashSale@itemUpdate' => ['marketing:flash-sale:manage'],
        'FlashSale@itemDelete' => ['marketing:flash-sale:manage'],
        'FlashSale@orderList' => ['marketing:flash-sale:manage'],
        'FlashSale@orderExportTaskCreate' => ['marketing:flash-sale:manage'],
        'FlashSale@orderExportTaskStatus' => ['marketing:flash-sale:manage'],
        'FlashSale@orderExportTaskRetry' => ['marketing:flash-sale:manage'],
        'FlashSale@orderExportTaskList' => ['marketing:flash-sale:manage'],
        'FlashSale@orderExportTaskDelete' => ['marketing:flash-sale:manage'],
        'FlashSale@statistics' => ['marketing:flash-sale:manage'],
        'FlashSale@riskLogList' => ['marketing:flash-sale:manage'],
        'FlashSale@riskSummary' => ['marketing:flash-sale:manage'],
        'FlashSale@riskHealthHistory' => ['marketing:flash-sale:manage'],
        'FlashSale@riskHealthThresholdGet' => ['marketing:flash-sale:manage'],
        'FlashSale@riskHealthThresholdUpdate' => ['marketing:flash-sale:manage'],
        'FlashSale@blacklistList' => ['marketing:flash-sale:manage'],
        'FlashSale@blacklistCreate' => ['marketing:flash-sale:manage'],
        'FlashSale@blacklistUpdate' => ['marketing:flash-sale:manage'],
        'FlashSale@blacklistDelete' => ['marketing:flash-sale:manage'],
        'ChannelDistribution@accountList' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@accountCreate' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@accountUpdate' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@accountToggle' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@accountTest' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@channelList' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@channelOptions' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@channelCreate' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@channelUpdate' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@channelToggle' => ['marketing:channel-distribution:account:manage'],
        'ChannelDistribution@taskList' => ['marketing:channel-distribution:task:view'],
        'ChannelDistribution@taskCreate' => ['marketing:channel-distribution:task:create'],
        'ChannelDistribution@taskDetail' => ['marketing:channel-distribution:task:view'],
        'ChannelDistribution@taskResubmit' => ['marketing:channel-distribution:task:create'],
        'ChannelDistribution@taskAudit' => ['marketing:channel-distribution:task:audit'],
        'ChannelDistribution@taskRetry' => ['marketing:channel-distribution:task:retry'],
        'ChannelDistribution@taskLogs' => ['marketing:channel-distribution:task:view'],
        'ChannelDistribution@callbackList' => ['marketing:channel-distribution:callback:view'],
        'ChannelDistribution@callbackDetail' => ['marketing:channel-distribution:callback:view'],
        'ChannelDistributionCallback@receive' => [],

        'Statistics@overview' => ['statistics:view'],
        'Statistics@user' => ['statistics:view'],
        'Statistics@content' => ['statistics:view'],
        'Statistics@payment' => ['statistics:view'],

        'Config@list' => ['config:manage'],
        'Config@update' => ['config:manage'],

        'system.Permission@list' => ['system:permission:manage'],
        'system.Permission@create' => ['system:permission:manage'],
        'system.Permission@update' => ['system:permission:manage'],
        'system.Permission@delete' => ['system:permission:manage'],

        'system.Menu@list' => ['system:menu:manage'],
        'system.Menu@create' => ['system:menu:manage'],
        'system.Menu@update' => ['system:menu:manage'],
        'system.Menu@delete' => ['system:menu:manage'],

        'system.Role@list' => ['system:role:manage'],
        'system.Role@create' => ['system:role:manage'],
        'system.Role@update' => ['system:role:manage'],
        'system.Role@delete' => ['system:role:manage'],
        'system.Role@permissions' => ['system:role:manage'],
        'system.Role@savePermissions' => ['system:role:manage'],

        'system.AdminUser@list' => ['system:admin-user:manage'],
        'system.AdminUser@create' => ['system:admin-user:manage'],
        'system.AdminUser@update' => ['system:admin-user:manage'],
        'system.AdminUser@delete' => ['system:admin-user:manage'],
        'system.AdminUser@saveRoles' => ['system:admin-user:manage'],
        'system.AdminUser@roles' => ['system:admin-user:manage'],
    ],
];
